[project]
name = "sphinx-demo"
version = "0.2.0"
description = "Demo Sphinx and bugs"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
authors = [{ name = "Randolf Scholz", email = "randolf.scholz@gmail.com" }]
dependencies = [
  "rust-just",
  "sphinx>=9.1.0",
  "sphinx-autoapi>=3.8.1",
  "sphinx-math-dollar>=1.3",
]

[build-system]
requires = ["uv_build>=0.12.16,<0.13"]
build-backend = "uv_build"
